[package]
name = "MtFmt"
version = "1.0.0"

[[package.file]]
category = "binarys"
file = ["target/*.a", "target/*.so"]
output = "bin"

[[package.file]]
category = "headers"
file = ["inc/**"]
output = "inc"

[[package.file]]
category = "sources"
file = ["src/**"]
output = "src"

[[package.file]]
file = ["LICENSE", "*.md", "version.txt"]
output = "."

[[action]]
mode = "pattern"
name = "update-c-version"
pattern = """
#if 1
//! major version
#define MSTR_VERSION_MAJOR {version:major}
#endif
#if 1
//! minor version
#define MSTR_VERSION_MINOR {version:minor}
#endif
#if 1
//! release version
#define MSTR_VERSION_RELEASE {version:release}
#endif
"""
pattern-beg = "//@ <autogen:version>"
pattern-end = "//@ </autogen:version>"
target = "./inc/mm_cfg.h"

[[action]]
mode = "pack"
name = "pack"
target = "mtfmt_release"

[[action]]
mode = "cmsispack"
name = "cmsis-pack"
target = "MTFMT"

[[action]]
mode = "pattern"
name = "update-version-text"
pattern = "{version:major}.{version:minor}.{version:release}"
target = "./version.txt"
