name: "Build Keil pack"

on:
  push:
    paths:
      - "src/**.c"
      - "inc/**.h"
      - ".github/workflows/keil-pack.yml"
  pull_request:
    branches: [master]
    paths:
      - "src/**.c"
      - "inc/**.h"
      - ".github/workflows/keil-pack.yml"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  pack-file:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
