name: Tests

on:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "Makefile"
      - ".github/workflows/tests.yml"
  pull_request:
    branches: [master]
    paths:
      - "**.c"
      - "**.h"
      - "Makefile"
      - ".github/workflows/tests.yml"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  tests:
    runs-on: ubuntu-latest
    name: "Tests"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
